### ISSUE TITLE
Java: Does not work in GraalVM native compilation

### ISSUE THREAD

**Issue by edeandrea** [microsoft/semantic-kernel-java#146]
**Describe the bug**
When trying to use this library with GraalVM native compilation the build fails.

See https://github.com/quarkusio/quarkus-super-heroes/actions/runs/6226135689/job/16898025230?pr=365

It won't let me post the entire log content because it is too long, so I'll attach it as a file instead.

[semantic kernel native error.txt](https://github.com/microsoft/semantic-kernel/files/12662617/semantic.kernel.native.error.txt)

**Comment by markwallace-microsoft** [comment]
Java issues moved to https://github.com/microsoft/semantic-kernel-java
