### ISSUE TITLE
Apply Azd Template Checklist to Customer Assistant sample

### ISSUE THREAD

**Issue by brunoborges** [microsoft/semantic-kernel-java#153]
https://github.com/Azure-Samples/azd-template-artifacts/blob/main/checklist.md

**Comment by d3r3kk** [comment]
@brunoborges where can we find the _checklist_ so that we can be sure we've applied it? ( `azd up` works with the sample now).

**Comment by d3r3kk** [comment]
@brunoborges - @johnoliver found it!

(added to description)
