### ISSUE TITLE
New Feature: Change OpenAIAsyncClient to be compatible with other Open AI-compatible GPTs such as Ollama

### ISSUE THREAD

**Issue by berdachuk** [microsoft/semantic-kernel-java#171]
Currently, in the NonAzureOpenAIClientImpl, the hardcoded OPEN_AI_ENDPOINT is "https://api.openai.com/v1".
So it is not possible to use OpenAIAsyncClient with other Open AI-compatible GPTs like Ollama.
It would be useful to create a customizable client version to work with different providers.

**Comment by johnoliver** [comment]
@berdachuk This is an issue with the azure-sdk-for-java, would need to be filed at: https://github.com/Azure/azure-sdk-for-java/issues/
