### ISSUE TITLE
Java: Create GitHub Releases for 1.2.0 and 1.2.2 on semantic-kernel-java repo

### ISSUE THREAD

**Issue by d3r3kk** [microsoft/semantic-kernel-java#180]
We don't yet have automation in place for adding Releases of the Semantic Kernel for Java on the GitHub repo. Please create a Release for the 1.2.0 and 1.2.2 releases we've recently published in our repo.

**Comment by dsgrieve** [comment]
Created 1.2.0 and 1.2.2 releases. These are _source_ only.
